apiVersion: 1

datasources:
  - name: my-influxdb
    type: influxdb
    orgId: 1
    url: "http://influxdb:8086"
    editable: true
    isDefault: true
    jsonData:
      httpMode: 'POST'
    secureJsonData:
      token: "DD85150B-3871-4622-8D14-45BFE743C270"
    jsonData:
      defaultBucket: "iot_data"
      httpMode: "POST"
      organization: "groupd"
      version: "Flux"
